name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hlf-version:
          - 2.2.0
          - 2.3.0
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./images/fabric-peer/${{matrix.hlf-version}}/Dockerfile
          push: true
          tags: kfsoftware/fabric-peer:amd64-${{matrix.hlf-version}}
